### ISSUE TITLE
stored procedure support?

### ISSUE THREAD

**Issue by skillio** [sc0ttkclark/exports-and-reports#1]
For in-depth reports I often use mysql views, and just select from the view. This lets me keep reports in version control also, rather than copying and pasting them every time into the wordpress admin.
However, mysql views don't support subselects and more complicated queries, so stored procedures seem to be the way to go to abstract the code out of the wordpress admin. 
Looked into it briefly by just adding "call procedure(foo)" in the sql, seemed like the hardcoded limit and count lookups in the UI class output were the first issues. I imagine a separate entry for stored procedure would be preferable, rather than just the sql text for "call". Thoughts?

**Comment by sc0ttkclark** [comment]
I haven't thought about procedure support before, I don't think there's an easy way to accomplish this in the current SQL handler and maintain the ability to paginate/filter.
