### ISSUE TITLE
No CSS for datepicker

### ISSUE THREAD

**Issue by gregoriopellegrino** [sc0ttkclark/exports-and-reports#10]
Hi,
the datepicker UI widget is shown, but without CSS (not really usable).

Thanks,
Gregorio

**Comment by jolora** [comment]
+1 

I came to report this too. Perhaps using type="date" on the input would be a good fallback for now?

**Comment by sc0ttkclark** [comment]
This is only going to get worse in WordPress 5.7 as the jQuery updates make the included jQuery Date picker functionality incompatible it looks like.

**Comment by sc0ttkclark** [comment]
Resolved in 0.8.7
