### ISSUE TITLE
Export issue with WP 5.1.1

### ISSUE THREAD

**Issue by rdaniel0** [sc0ttkclark/exports-and-reports#12]
Seems like none of the exports work in WP 5.1.1

Checked the SQL query shown with &debug=1 in phpmyadmin and it works fine.

Seems like there is an issue in wp-admin-ui/Admin.class.php Line 1519 and 1521: The 
$export_file variable is defined only in the child scopes leaving it undefined at those lines. 

After fixing that in my local copy I tried exporting again to get the following error page on Chrome, shown in a new tab
`
The webpage at http://wpdevelopment/wp-admin/admin-ajax.php?action=wp_admin_ui_export&exports_and_reports_download=1&_wpnonce=8f98e93c5b&exports_and_reports_export=test_table_05-01-2019_02-09-35_VuGJW.csv might be temporarily down or it may have moved permanently to a new web address.
ERR_UNSAFE_REDIRECT
`

**Comment by sc0ttkclark** [comment]
Resolved in 0.8.3 out shortly, thanks for the help!
