### ISSUE TITLE
passing variables with url

### ISSUE THREAD

**Issue by eladwass** [sc0ttkclark/exports-and-reports#13]
Hi

Is there an option to pass variables through the URL so it will be replaced in my predefined SQL query? 
for instance:

Select * from TABLE
where field == %%VARIABLE_NUM_1%%

and then sending in the url "http://.........VARIABLE_NUM_1='blabla'....."

thanks ahead
elad

**Comment by sc0ttkclark** [comment]
Yes, but don't add it to the WHERE clause. Just define the column below the query in the list of columns and hide it so it doesn't show in the report/table, but make it filterable. Then you can use CSS to hide the input field if you'd like but that's what lets a field become filterable automatically.
