### ISSUE TITLE
This plugin doesn't seem to work on windows due to some \ instead of /

### ISSUE THREAD

**Issue by ZelonGames** [sc0ttkclark/exports-and-reports#16]
When I try to export a report I get ERR_UNSAFE_REDIRECT error. To fix this I had to go to the Admin.class.php file and replace line 23:

wp_redirect( str_replace( WP_ADMIN_UI_EXPORT_DIR, WP_ADMIN_UI_EXPORT_URL, $file ) );

With this:

wp_redirect( str_replace("\\", "/", str_replace( str_replace("/", "\\", WP_ADMIN_UI_EXPORT_DIR), WP_ADMIN_UI_EXPORT_URL, $file ) ));

To make sure that all slashes are forward slashes and then everything worked just fine. I have this plugin on a linux server as well and I didn't have to change anything on the linux server so it seems to be a windows issue.

**Comment by sc0ttkclark** [comment]
Thanks for the report, I will get this fixed in the next release

**Comment by sc0ttkclark** [comment]
Resolved in 0.8.7
