### ISSUE TITLE
Excel export of numeric fields

### ISSUE THREAD

**Issue by noelhunter** [sc0ttkclark/exports-and-reports#18]
Fields defined as numeric seem to be included in the Excel export as text values

**Comment by sc0ttkclark** [comment]
This is correct, all exports are enclosed in quotes like: `"some value","123"`

I could look at adding some more logic here to detect the type of the field (as defined by the report config itself) and if it's numeric it could attempt to tell the XLSX that it's numeric.

**Comment by sc0ttkclark** [comment]
Something in this area might do the trick but I'd have to do more testing: https://github.com/sc0ttkclark/exports-and-reports/blob/master/wp-admin-ui/Admin.class.php#L1449

**Comment by sc0ttkclark** [comment]
Resolved in 0.8.7
