### ISSUE TITLE
Noob: How to get the post's thumbnail?

### ISSUE THREAD

**Issue by uebmaster** [sc0ttkclark/exports-and-reports#19]
I´m almost using the default query.

But i want to get the post's thumbnail, how can i do it?

This is the query:

SELECT ID,post_title,post_name,post_date,post_content,the_post_thumbnail FROM wp_posts WHERE post_type='post' AND post_status='publish'

I've added "the_post_thumbnail" but i get nothing more than the message "No items found"

What is the correct query?

Thanks in advance.

**Comment by dxdc** [comment]
@uebmaster I think your question is better asked in a Wordpress-specific forum. You should test your SQL; if your SQL fails, this plugin certainly won't help. Something like this approach is what you need to be able to pull the thumbnail:

https://dbarnwal.wordpress.com/2014/09/05/get-featured-image-url-direct-using-mysql-query-in-wordpress/

**Comment by sc0ttkclark** [comment]
the_post_thumbnail is not a column in the wp_posts table.

You CAN try adding something like:

`SELECT ID, post_title, post_name, post_date, post_content, ID AS post_id_for_thumbnail FROM wp_posts WHERE post_type = 'post' AND post_status = 'publish'`

Then set the display function for the `post_id_for_thumbnail` field to: `get_the_post_thumbnail`

This would allow the automatic output of the thumbnail into the table.
