### ISSUE TITLE
Multiple errors and warnings with WP_DEBUG = true

### ISSUE THREAD

**Issue by robgeorgeuk** [sc0ttkclark/exports-and-reports#2]
Hey Scott,

Thanks for the plugin, I think this will save me a lot of time.

I have installed the plugin on a fresh WP install 4.9.1 with WP_DEBUG = true and I'm seeing a lot of warnings and errors that make the plugin unusable.

There are quite a few but they are mostly array to string errors and undefined offset errors around the listing of the group name.

Also the 'reset now' (and prob 'clear now') features try to use $wp_filesystem which isn't available.

Is this something you could take a look at? I think it would be easy to recreate, I'm running Nginx and PHP 7.1 if that makes any difference.

Best regards,
Rob

**Comment by sc0ttkclark** [comment]
Sorry for the delay, good points for sure. I need to revisit this plugin and update it with my phpcs fixes and ensure $wp_filesystem gets setup via `WP_Filesystem()` if it's empty.

**Comment by sc0ttkclark** [comment]
Try the latest 0.8.0 release (on master, tagged, and released to wordpress.org), this has been resolved there.
