### ISSUE TITLE
Support for CTE, variables, EXECUTE IMMEDIATE

### ISSUE THREAD

**Issue by dxdc** [sc0ttkclark/exports-and-reports#21]
Trying to run queries like this (also tried w/ CTE) fails without a really specific error. The SQL runs perfectly against the raw database, but not within this plugin.

I think part of the problem is the use of `SQL_CALC_FOUND_ROWS` which I've seen inserted during my testing, but would be grateful for any advice on how to get these kinds of queries to run.

```sql
SET @cols = (SELECT GROUP_CONCAT(CONCAT('`', COLUMN_NAME, '`')) FROM information_schema.COLUMNS WHERE TABLE_NAME='test_table_1' AND (COLUMN_NAME NOT LIKE '%Revenue%'));
EXECUTE IMMEDIATE CONCAT('SELECT ', @cols, ' FROM `test_table_1`');
```

**Comment by sc0ttkclark** [comment]
WordPress does not support multiple queries in the same query request. All of our report queries are single-query executing. The other part is that SQL_CALC_FOUND_ROWS does get added automatically so it can handle totals on the page and pagination stuff. There's no workaround for either of these at this point.

**Comment by dxdc** [comment]
> WordPress does not support multiple queries in the same query request

Which function are you using for this? A lot of times you can separate it with a semicolon, but it depends on what's being run. It leads me to another thought though.

Suppose you could add a custom SQL query that would be stored in another variable like `%%QUERY_PARAM1%%`

Then, this could be re-used in the main query. That doesn't necessarily fix the usage of CTE, but it's also confusing to me why CTE's dont work because that would just be a single expression.

I also can't remember specifics, but I think that subqueries sometimes gave me trouble.

**Comment by sc0ttkclark** [comment]
There's no filter available after processing is done on the SQL but before the SQL query is executed except for the super generic `'query'` filter which is in `WPDb::_do_query()` itself.

As for multiple queries, WordPress uses calls to `mysqli_query` and `mysql_query` which both don't support multiple statements in the same call.

**Comment by dxdc** [comment]
@sc0ttkclark 

What about: `mysqli_multi_query($wpdb->dbh, $raw_sql_query)`? This supports multiple statements.

**Comment by sc0ttkclark** [comment]
That sounds cool, it's just not yet built into WordPress itself. I don't have any plans to add anything beyond the WPDb capabilities here as it's a lot to take ownership of for long term support.

**Comment by dxdc** [comment]
It does work with Wordpress, you just reference `global $wpdb;` and then the query, e.g., `mysqli_multi_query($wpdb->dbh, 'SELECT * FROM table_1; SELECT * FROM table_2;')`

**Comment by sc0ttkclark** [comment]
You are correct, you can write that kind of code and it'll work, but unfortunately that's not something WordPress itself supports with it's query handling. It's all routed through `mysqli_query` instead, and I don't have any plans currently to support multiple queries in any other way. Exports and Reports calls `$wpdb->get_results( $sql )` in the area that this query is used.

**Comment by sc0ttkclark** [comment]
If you'd like to take a crack at a PR that does the checking for multiple query statements and then add a `get_results`-like method that copies some of the functionality but ultimately calls `mysqli_multi_query`, you could. I just don't have plans myself to spend that time at this point.

**Comment by sc0ttkclark** [comment]
Here is where the code runs the `get_results`: https://github.com/sc0ttkclark/exports-and-reports/blob/main/wp-admin-ui/Admin.class.php#L2061

You could also potentially add a filter to be able to return an empty string for the `$calc_found_sql` at: https://github.com/sc0ttkclark/exports-and-reports/blob/main/wp-admin-ui/Admin.class.php#L1719 and it might also need something to check for a non-empty `$calc_found_sql` before running the follow-up query here: https://github.com/sc0ttkclark/exports-and-reports/blob/main/wp-admin-ui/Admin.class.php#L2063

**Comment by dxdc** [comment]
Thx! Let me see if I can experiment with this a bit more.

**Comment by dxdc** [comment]
@sc0ttkclark thanks for your advice.

I came up with a subtle workaround, which I've created a PR for.

Essentially, it will look for `;;` as a delimiter. I decided this was more safe (vs. using just a single `;`) because we are not really parsing SQL and it's possible someone may use a semi-colon in a column name, for example. This isn't perfect either, but maybe it's workable.

Using this tweak, the following works great (with mariadb).

```sql
SET @cols = 'id';;
EXECUTE IMMEDIATE CONCAT(' SELECT ', @cols, ' FROM `my_table_1` LIMIT %%LIMIT%%')
```

Also, this kind of technique could be used to create a temporary table, with the last command being a variant of `SELECT * FROM temp_table_2`.

Let me know what you think of this approach.

A few other things I've realized, in working with the code a bit more:

1. Maybe helpful to note somewhere that `get_results` in this capacity discards duplicate column names. It's a Wordpress "feature". This can get annoying when joining tables... though maybe the solution above is one way to tackle it. There may be some way to use `ARRAY_N` instead of `ARRAY_A` which would return the full dataset, and then reformat with new column names if duplicates are found.

https://github.com/sc0ttkclark/exports-and-reports/blob/main/wp-admin-ui/Admin.class.php#L2061

2. It looks like you eliminate newlines, spaces, etc. in your code. I submitted a separate PR for this, using preg_replace instead, although maybe using `;;\n` as a delimiter could be preferred if we still had newlines around to work with.

**Comment by dxdc** [comment]
Btw, one note:

There is a space before `SELECT` in the query I provided, because of how your detection works to insert `SQL_CALC_FOUND_ROWS`. Without that space, it won't be inserted. I didn't completely understand the logic so didn't want to disturb it... writing a separate `COUNT(*)` query would be better anyway.

In this case, I could write instead:
```sql
SELECT COUNT(*) FROM `my_table_1`
```

**Comment by sc0ttkclark** [comment]
This can be accomplished by adding a filter/action in the area where the PR was. Perhaps by filtering `$sql` before it runs you could do what you need and adjust `$sql` accordingly.
