### ISSUE TITLE
Undefined index: page_orientation

### ISSUE THREAD

**Issue by dxdc** [sc0ttkclark/exports-and-reports#27]
Hi @sc0ttkclark 

I'm seeing this PHP warning in logs, though not sure which report is triggering it:

```
PHP Notice:  Undefined index: page_orientation in /var/www/html/wp-content/plugins/exports-and-reports/exports-and-reports.php on line 1258
```

Also, any chance of bumping the new release to include the changes from March?

**Comment by sc0ttkclark** [comment]
Sure, will do this week. Thanks for your patience :)

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/sc0ttkclark/exports-and-reports/pull/29
