### ISSUE TITLE
Permissions issue when mixing group permissions with individual reports

### ISSUE THREAD

**Issue by dxdc** [sc0ttkclark/exports-and-reports#28]
Some of the reports have been disappearing from user accounts, and as far as I can tell, it's caused by something like this:

- Create a reports group. Grant permission to a single/multiple roles.
- Create multiple reports and assign to above group.
- Grant permission to a group (e.g., same group from the first step) to just one of the reports
- Login as that user, this group will not be visible.

Perhaps I'm somewhat unclear on how the reporting permissions are working since they could be specified at the group level and/or the individual level, but would appreciate any guidance on solving this one. Thanks @sc0ttkclark !

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/sc0ttkclark/exports-and-reports/pull/29
