### ISSUE TITLE
Code requires vendor/autoload.php

### ISSUE THREAD

**Issue by fuzzybo** [sc0ttkclark/exports-and-reports#35]
After downloading the 0.9.3 .zip file and installing it in our WP install (WP 6.1.1, PHP 7.4), both by uploading the .zip using Plugins >> Add New >> Upload Plugin, and via FTP, then when activating the plugin, an error was raised.
Error message:
Plugin could not be activated because it triggered a fatal error.
Warning: require_once(<domain>/httpdocs/wordpress/wp-content/plugins/exports-and-reports-main/vendor/autoload.php): failed to open stream: No such file or directory in <domain>/httpdocs/wordpress/wp-content/plugins/exports-and-reports-main/exports-and-reports.php on line 36
This folder/file is not included in the .zip or the repository. As one new to Git and WP plugins, am I missing something obvious?

**Comment by fuzzybo** [comment]
The vendor folder, and its contents, are created by Composer. https://roots.io/using-composer-with-wordpress/

**Comment by sc0ttkclark** [comment]
Sorry I haven't gone through to finish getting everything ready for release. The GitHub repo does not have the vendor folder included as that's installed through Composer itself prior to preparing for WordPress.org

**Comment by fuzzybo** [comment]
Thanks for replying. I love your plugin! 

I use Composer to update our Magento stores, so I am a bit familiar with it. I was unaware that it was also used with WP plugins, until I ran into it with your plugin. TIL, and now I have ++ experience points :-)

Thanks again for your plugin.

Best regards
Steve Cooke
