### ISSUE TITLE
Can't get Groups to work

### ISSUE THREAD

**Issue by ChristianKubstrup** [sc0ttkclark/exports-and-reports#8]
When I create a 2nd group it is added to the Reports menu as it should, but clicking on this 2nd group it "links" back to the first group created (I have assigned reports to the group). Is this is known issue? Currently I am forced to keep all reports in one group = one long list :-(

**Comment by sc0ttkclark** [comment]
I'm not sure I was aware of this, I'll take a look at it the next chance I get. It should be within the coming week or weekend after. I apologize I don't have more time to look at this immediately.

**Comment by ChristianKubstrup** [comment]
?

Hi Scott

Thanks for your reply. Let me know if more info or screen dumps would be helpful.

Best

Christian





________________________________
Fra: Scott Kingsley Clark <notifications@github.com>
Sendt: 13. februar 2019 20:37
Til: sc0ttkclark/exports-and-reports
Cc: christian Kubstrup; Author
Emne: Re: [sc0ttkclark/exports-and-reports] Can't get Groups to work (#8)


I'm not sure I was aware of this, I'll take a look at it the next chance I get. It should be within the coming week or weekend after. I apologize I don't have more time to look at this immediately.

-

**Comment by ChristianKubstrup** [comment]
Hi Scott
Any luck finding time to look at the “Report Group” issue?
Best
Christian

Christian Kubstrup 
Martinsvej 11, 8751 Gedved
Tlf.: 5319 4743

Den 13. feb. 2019 kl. 20.37 skrev Scott Kingsley Clark <notifications@github.com>:

I'm not sure I was aware of this, I'll take a look at it the next chance I get. It should be within the coming week or weekend after. I apologize I don't have more time to look at this immediately.

**Comment by sc0ttkclark** [comment]
Fixed in 0.8.3 which is going out shortly
